/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.view;

import com.mycompany.classes.Quarto;
import com.mycompany.connection.InserirDAO;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import static javax.swing.SwingConstants.CENTER;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author User
 */
public class menuHotel extends javax.swing.JFrame {

    /**
     * Creates new form menuHotel
     */
    public menuHotel() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) Table_ocupados.getModel();
        Table_ocupados.setRowSorter(new TableRowSorter(modelo));
        lerTableOcupados();
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        alinhaLabel_Table(0);
        alinhaLabel_Table(1);
        alinhaLabel_Table(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_menu = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        labelFazerCheckin = new java.awt.Label();
        labelFazerCheckout = new java.awt.Label();
        labelCadastraHospede = new java.awt.Label();
        ScrollPane_ocupados = new javax.swing.JScrollPane();
        Table_ocupados = new javax.swing.JTable();
        Label_Ocupados = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Panel_menu.setBackground(new java.awt.Color(102, 102, 102));

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hotel");

        labelFazerCheckin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelFazerCheckin.setForeground(new java.awt.Color(255, 255, 153));
        labelFazerCheckin.setText("Fazer checkIn");
        labelFazerCheckin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFazerCheckinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelFazerCheckinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelFazerCheckinMouseExited(evt);
            }
        });

        labelFazerCheckout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelFazerCheckout.setForeground(new java.awt.Color(255, 255, 153));
        labelFazerCheckout.setText("Fazer checkOut");
        labelFazerCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFazerCheckoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelFazerCheckoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelFazerCheckoutMouseExited(evt);
            }
        });

        labelCadastraHospede.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelCadastraHospede.setForeground(new java.awt.Color(255, 255, 153));
        labelCadastraHospede.setText("Cadastrar Hospede");
        labelCadastraHospede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCadastraHospedeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelCadastraHospedeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelCadastraHospedeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelFazerCheckin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
            .addComponent(labelFazerCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelCadastraHospede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(135, 135, 135)
                .addComponent(labelFazerCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelFazerCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelCadastraHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Table_ocupados.setBackground(new java.awt.Color(155, 155, 155));
        Table_ocupados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "N° Quarto", "N° Pessoas", "ID Hospede Atual"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table_ocupados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Table_ocupados.setDragEnabled(true);
        Table_ocupados.setEnabled(false);
        Table_ocupados.setGridColor(new java.awt.Color(0, 0, 0));
        Table_ocupados.setShowGrid(true);
        Table_ocupados.setShowVerticalLines(false);
        ScrollPane_ocupados.setViewportView(Table_ocupados);
        if (Table_ocupados.getColumnModel().getColumnCount() > 0) {
            Table_ocupados.getColumnModel().getColumn(0).setHeaderValue("N° Quarto");
            Table_ocupados.getColumnModel().getColumn(1).setHeaderValue("N° Pessoas");
            Table_ocupados.getColumnModel().getColumn(2).setHeaderValue("ID Hospede Atual");
        }

        Label_Ocupados.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        Label_Ocupados.setText("Quartos ocupados");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Atualizar lista");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("x");
        jLabel4.setToolTipText("");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_menuLayout = new javax.swing.GroupLayout(Panel_menu);
        Panel_menu.setLayout(Panel_menuLayout);
        Panel_menuLayout.setHorizontalGroup(
            Panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_menuLayout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_menuLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(ScrollPane_ocupados))
                    .addGroup(Panel_menuLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(Label_Ocupados)
                        .addGap(0, 246, Short.MAX_VALUE))
                    .addGroup(Panel_menuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_menuLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addContainerGap())))))
        );
        Panel_menuLayout.setVerticalGroup(
            Panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_menuLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(20, 20, 20)
                .addComponent(Label_Ocupados)
                .addGap(53, 53, 53)
                .addComponent(ScrollPane_ocupados, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47))
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        lerTableOcupados();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void labelFazerCheckinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFazerCheckinMouseEntered
        labelFazerCheckin.setBackground(corbgMenu);
    }//GEN-LAST:event_labelFazerCheckinMouseEntered

    private void labelFazerCheckinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFazerCheckinMouseExited
        labelFazerCheckin.setBackground(Color.BLACK);
    }//GEN-LAST:event_labelFazerCheckinMouseExited

    private void labelFazerCheckinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFazerCheckinMouseClicked
        InserirDAO dao = new InserirDAO();
        List<Quarto> quartos = new ArrayList<>();
        Quarto quarto = new Quarto();
        int i;
        quartos = dao.readQuartos();
        if (quartos.isEmpty()) {
            for (i = 0; i < 16; i++) {
                quarto.setNumeroQuarto(i + 1);
                quarto.setQtd_Pessoa(0);
                quarto.setQtd_Cama(2);
                quarto.setDiaria(200);
                quarto.setCama_casal("sim");
                quarto.setStatus(0);
                quarto.setTipodeQuarto(0);
                quarto.setHospede_Atual(0);
                dao.cretae(quarto);
            }
            for (i = 15; i < 31; i++) {
                quarto.setNumeroQuarto(i + 1);
                quarto.setQtd_Pessoa(0);
                quarto.setQtd_Cama(2);
                quarto.setDiaria(200);
                quarto.setCama_casal("sim");
                quarto.setStatus(0);
                quarto.setTipodeQuarto(1);
                quarto.setHospede_Atual(0);
                dao.cretae(quarto);
            }
        }
        new Checkin().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_labelFazerCheckinMouseClicked

    
    Color corbgMenu = new Color(102,102,102);
    
    private void labelFazerCheckoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFazerCheckoutMouseEntered
        labelFazerCheckout.setBackground(corbgMenu);
    }//GEN-LAST:event_labelFazerCheckoutMouseEntered

    private void labelFazerCheckoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFazerCheckoutMouseExited
        labelFazerCheckout.setBackground(Color.BLACK);
    }//GEN-LAST:event_labelFazerCheckoutMouseExited

    private void labelCadastraHospedeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCadastraHospedeMouseEntered
        labelCadastraHospede.setBackground(corbgMenu);
    }//GEN-LAST:event_labelCadastraHospedeMouseEntered

    private void labelCadastraHospedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCadastraHospedeMouseClicked
        new CadastroHospede().setVisible(true);
    }//GEN-LAST:event_labelCadastraHospedeMouseClicked

    private void labelCadastraHospedeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCadastraHospedeMouseExited
        labelCadastraHospede.setBackground(Color.BLACK);
    }//GEN-LAST:event_labelCadastraHospedeMouseExited

    private void labelFazerCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFazerCheckoutMouseClicked
        new CheckOut().setVisible(true);
    }//GEN-LAST:event_labelFazerCheckoutMouseClicked

    public void lerTableOcupados() {
        DefaultTableModel modelo = (DefaultTableModel) Table_ocupados.getModel();
        modelo.setRowCount(0);
        InserirDAO dao = new InserirDAO();
        for (Quarto q : dao.readQuartos()) {
            if (q.getStatus() == 1) {
                modelo.addRow(new Object[]{
                    q.getNumeroQuarto(),
                    q.getQtd_Pessoa(),
                    q.getHospede_Atual()

                });
            }
        }
    }

    public void alinhaLabel_Table(int numeroColuna) {
        Table_ocupados.getTableHeader().setBackground(new Color(155, 155, 155));
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        Table_ocupados.getColumnModel().getColumn(numeroColuna).setCellRenderer(centralizado);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new menuHotel().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Ocupados;
    private javax.swing.JPanel Panel_menu;
    private javax.swing.JScrollPane ScrollPane_ocupados;
    private javax.swing.JTable Table_ocupados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private java.awt.Label labelCadastraHospede;
    private java.awt.Label labelFazerCheckin;
    private java.awt.Label labelFazerCheckout;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
