/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.view;

import com.mycompany.classes.Quarto;
import com.mycompany.connection.InserirDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author User
 */
public class menuHotel extends javax.swing.JFrame {

    /**
     * Creates new form menuHotel
     */
    public menuHotel() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) Table_ocupados.getModel();
        Table_ocupados.setRowSorter(new TableRowSorter(modelo));
        lerTableOcupados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        LabelCadastro = new javax.swing.JLabel();
        LabelFazerchekin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ScrollPane_ocupados = new javax.swing.JScrollPane();
        Table_ocupados = new javax.swing.JTable();
        Label_Ocupados = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hotel");

        LabelCadastro.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        LabelCadastro.setForeground(new java.awt.Color(255, 255, 153));
        LabelCadastro.setText("Cadastrar Hospede");
        LabelCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCadastroMouseClicked(evt);
            }
        });

        LabelFazerchekin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LabelFazerchekin.setForeground(new java.awt.Color(255, 255, 153));
        LabelFazerchekin.setText("Fazer checkIn");
        LabelFazerchekin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelFazerchekinMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 153));
        jLabel3.setText("Fazer checkOut");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(LabelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelFazerchekin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(96, 96, 96)
                .addComponent(LabelCadastro)
                .addGap(26, 26, 26)
                .addComponent(LabelFazerchekin)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        Table_ocupados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "N° Quarto", "N° Pessoas", "ID Hospede Atual"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ScrollPane_ocupados.setViewportView(Table_ocupados);

        Label_Ocupados.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        Label_Ocupados.setText("Quartos ocupados");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Atualizar lista");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(ScrollPane_ocupados, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(Label_Ocupados)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Label_Ocupados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane_ocupados, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LabelCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCadastroMouseClicked
        new CadastroHospede().setVisible(true);

    }//GEN-LAST:event_LabelCadastroMouseClicked

    private void LabelFazerchekinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelFazerchekinMouseClicked
        InserirDAO dao = new InserirDAO();
        List<Quarto> quartos = new ArrayList<>();
        Quarto quarto = new Quarto();
        int i;
        quartos = dao.readQuartos();
        if (quartos.isEmpty()) {
            for (i = 0; i < 16; i++) {
                quarto.setNumeroQuarto(i + 1);
                quarto.setQtd_Pessoa(0);
                quarto.setQtd_Cama(2);
                quarto.setDiaria(200);
                quarto.setCama_casal("sim");
                quarto.setStatus(0);
                quarto.setTipodeQuarto(0);
                quarto.setHospede_Atual(0);
                dao.cretae(quarto);
            }
            for (i = 15; i < 31; i++) {
                quarto.setNumeroQuarto(i + 1);
                quarto.setQtd_Pessoa(0);
                quarto.setQtd_Cama(2);
                quarto.setDiaria(200);
                quarto.setCama_casal("sim");
                quarto.setStatus(0);
                quarto.setTipodeQuarto(1);
                quarto.setHospede_Atual(0);
                dao.cretae(quarto);
            }
        }
        new Checkin().setVisible(true);

    }//GEN-LAST:event_LabelFazerchekinMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        lerTableOcupados();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new CheckOut().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    public void lerTableOcupados() {
        DefaultTableModel modelo = (DefaultTableModel) Table_ocupados.getModel();
        modelo.setRowCount(0);
        InserirDAO dao = new InserirDAO();
        for (Quarto q : dao.readQuartos()) {
            if (q.getStatus() == 1) {
                modelo.addRow(new Object[]{
                    q.getNumeroQuarto(),
                    q.getQtd_Pessoa(),
                    q.getHospede_Atual()

                });
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new menuHotel().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCadastro;
    private javax.swing.JLabel LabelFazerchekin;
    private javax.swing.JLabel Label_Ocupados;
    private javax.swing.JScrollPane ScrollPane_ocupados;
    private javax.swing.JTable Table_ocupados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
